name: ROS2 CI

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  test_environment:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        ros_distribution: [humble]

        include:
          - ros_distribution: humble
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: setup directories
        run: mkdir -p ros_ws/src

      - name: checkout
        uses: actions/checkout@v3
        with:
          path: ros_ws/src

      - name: build and test
        uses: ros-tooling/action-ros-ci@master
        with:
          package-name: h264_image_transport h264_msgs
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""